"""add poland_order_item_orders

Revision ID: 5d55aefadf79
Revises: pk2026080401
Create Date: 2026-08-06 15:32:42.224547

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5d55aefadf79'
down_revision = 'pk2026080401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poland_order_item_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poland_order_item_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['poland_order_item_id'], ['poland_order_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poland_order_item_id', 'order_id', name='uq_poland_order_item_order')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poland_order_item_orders')
    # ### end Alembic commands ###
