"""Add has_seen_tour to User model

Revision ID: c501f414652a
Revises: 168e362bb7c8
Create Date: 2026-03-29 00:07:15.496484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c501f414652a'
down_revision = '168e362bb7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_seen_tour', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_seen_tour')
    # ### end Alembic commands ###
